"""Stage-based badminton simulator with 2D court movement and 3D shuttle flight."""

from badminton1d.action_space import DiscreteActionConfig, DiscreteActionMapper
from badminton1d.agents import GreedyReceiver, RandomValidHitter, SafeHitter, StageAgent
from badminton1d.config import SimulationConfig
from badminton1d.curricula import (
    DEFAULT_DEFENSIVE_CURRICULUM_NAME,
    DEFAULT_DEFENSIVE_CURRICULUM_OPPONENT_PATH,
    DefensiveBackcourtCurriculumConfig,
    DefensiveBackcourtPhase,
    TrainingCurriculumSpec,
    available_training_curricula,
    build_training_curriculum,
)
from badminton1d.env import Badminton1DEnv, default_initial_state
from badminton1d.match import MatchConfig, MatchResult, MatchScore, RallyResult, reset_for_serve, run_match, run_rally
from badminton1d.obs import ObservationConfig, ObservationEncoder
from badminton1d.opponents import (
    GreedyDiscretePolicy,
    GreedyInterceptOpponent,
    RandomDiscretePolicy,
    RandomValidOpponent,
    SafeDiscretePolicy,
    SafeHeuristicOpponent,
    make_baseline_policy,
    make_opponent,
)
from badminton1d.playback import FrameSnapshot, MatchTrace, RallyTrace, StageTrace, build_match_trace, build_rally_trace, interpolate_stage
from badminton1d.pressure import (
    MatchShotPressure,
    ShotPressureIndex,
    ShotPressureWeights,
    evaluate_match_pressure,
    shot_pressure_from_record,
    shot_pressure_from_stage_trace,
    summarize_match_pressure,
)
from badminton1d.reset_sampling import ResetSamplingConfig
from badminton1d.reward_shaping import (
    DefensiveLiftRewardConfig,
    LoopPenaltyConfig,
    NetProximityRewardConfig,
    OpponentTravelRewardConfig,
    PressureRewardConfig,
    ReturnDepthRewardConfig,
)
from badminton1d.render import ScoreboardOverlay
from badminton1d.selfplay import CheckpointPool, FixedCheckpointOpponent, FrozenCheckpointOpponent, LiveModelOpponent, MixedCheckpointOpponent
from badminton1d.rl_env import BadmintonRLEnv, RLEnvConfig, RewardConfig
from badminton1d.shot_generators import (
    ANGLE_BIN_NAMES,
    ANGLE_BIN_NAMES_1D,
    ANGLE_BIN_NAMES_2D,
    LANDING_ZONE_COUNT_1D,
    POWER_BIN_NAMES,
    POWER_BIN_NAMES_1D,
    SHOT_NAME_ORDER,
    TacticAction1D,
    TacticAction2D,
    TacticLookup1D,
    TacticLookup2D,
    TacticRuntimeConfig,
    infer_shot_name,
    name_velocity_shot,
)
from badminton1d.state import ShotAction, StageRecord, StageState
from badminton1d.video import (
    TrainingProgressSample,
    VideoExportResult,
    export_match_video,
    export_rally_video,
    export_training_progress_video,
    render_match_frame,
    render_video_frame,
)

__all__ = [
    "Badminton1DEnv",
    "BadmintonRLEnv",
    "DiscreteActionConfig",
    "DiscreteActionMapper",
    "DEFAULT_DEFENSIVE_CURRICULUM_NAME",
    "DEFAULT_DEFENSIVE_CURRICULUM_OPPONENT_PATH",
    "DefensiveLiftRewardConfig",
    "DefensiveBackcourtCurriculumConfig",
    "DefensiveBackcourtPhase",
    "FrameSnapshot",
    "FixedCheckpointOpponent",
    "FrozenCheckpointOpponent",
    "GreedyDiscretePolicy",
    "GreedyReceiver",
    "GreedyInterceptOpponent",
    "LiveModelOpponent",
    "MatchConfig",
    "MatchResult",
    "MatchShotPressure",
    "MatchScore",
    "MatchTrace",
    "ObservationConfig",
    "ObservationEncoder",
    "CheckpointPool",
    "LoopPenaltyConfig",
    "MixedCheckpointOpponent",
    "NetProximityRewardConfig",
    "OpponentTravelRewardConfig",
    "RandomValidHitter",
    "RandomDiscretePolicy",
    "RandomValidOpponent",
    "ResetSamplingConfig",
    "PressureRewardConfig",
    "RewardConfig",
    "ReturnDepthRewardConfig",
    "RallyResult",
    "RallyTrace",
    "RLEnvConfig",
    "SafeDiscretePolicy",
    "SafeHitter",
    "SafeHeuristicOpponent",
    "ShotAction",
    "ShotPressureIndex",
    "ShotPressureWeights",
    "SHOT_NAME_ORDER",
    "SimulationConfig",
    "ScoreboardOverlay",
    "StageAgent",
    "StageRecord",
    "StageState",
    "StageTrace",
    "TacticAction1D",
    "TacticAction2D",
    "TacticLookup1D",
    "TacticLookup2D",
    "TacticRuntimeConfig",
    "TrainingCurriculumSpec",
    "TrainingProgressSample",
    "VideoExportResult",
    "ANGLE_BIN_NAMES",
    "ANGLE_BIN_NAMES_1D",
    "ANGLE_BIN_NAMES_2D",
    "LANDING_ZONE_COUNT_1D",
    "POWER_BIN_NAMES",
    "POWER_BIN_NAMES_1D",
    "available_training_curricula",
    "build_match_trace",
    "build_training_curriculum",
    "build_rally_trace",
    "default_initial_state",
    "export_match_video",
    "export_rally_video",
    "export_training_progress_video",
    "evaluate_match_pressure",
    "interpolate_stage",
    "make_baseline_policy",
    "make_opponent",
    "infer_shot_name",
    "name_velocity_shot",
    "render_match_frame",
    "render_video_frame",
    "reset_for_serve",
    "run_match",
    "run_rally",
    "shot_pressure_from_record",
    "shot_pressure_from_stage_trace",
    "summarize_match_pressure",
]
